export const ADD_VEHICLE = "ADD_VEHICLE";
export const UPDATE_VEHICLE = "UPDATE_VEHICLE";
export const DELETE_VEHICLE = "DELETE_VEHICLE";
export const FETCH_MAKES_BEGIN = "FETCH_MAKES_BEGIN";
export const FETCH_MAKES_SUCCESS = "FETCH_MAKES_SUCCESS";
export const FETCH_MAKES_FAILURE = "FETCH_MAKES_FAILURE";